// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: delay.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "delay.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace delayMessage {

namespace {

const ::google::protobuf::Descriptor* DelayMsg_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  DelayMsg_reflection_ = NULL;

}  // namespace


void protobuf_AssignDesc_delay_2eproto() GOOGLE_ATTRIBUTE_COLD;
void protobuf_AssignDesc_delay_2eproto() {
  protobuf_AddDesc_delay_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "delay.proto");
  GOOGLE_CHECK(file != NULL);
  DelayMsg_descriptor_ = file->message_type(0);
  static const int DelayMsg_offsets_[24] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(DelayMsg, cmd_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(DelayMsg, str_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(DelayMsg, msg_id_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(DelayMsg, send_time_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(DelayMsg, uav_id_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(DelayMsg, lat_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(DelayMsg, lon_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(DelayMsg, alt_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(DelayMsg, vx_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(DelayMsg, vy_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(DelayMsg, vz_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(DelayMsg, x_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(DelayMsg, y_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(DelayMsg, z_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(DelayMsg, w_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(DelayMsg, gps_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(DelayMsg, flight_status_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(DelayMsg, is_from_keyboard_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(DelayMsg, target_lat_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(DelayMsg, target_lon_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(DelayMsg, target_alt_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(DelayMsg, vl_x_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(DelayMsg, vl_y_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(DelayMsg, vl_z_),
  };
  DelayMsg_reflection_ =
    ::google::protobuf::internal::GeneratedMessageReflection::NewGeneratedMessageReflection(
      DelayMsg_descriptor_,
      DelayMsg::default_instance_,
      DelayMsg_offsets_,
      -1,
      -1,
      -1,
      sizeof(DelayMsg),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(DelayMsg, _internal_metadata_),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(DelayMsg, _is_default_instance_));
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_delay_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
      DelayMsg_descriptor_, &DelayMsg::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_delay_2eproto() {
  delete DelayMsg::default_instance_;
  delete DelayMsg_reflection_;
}

void protobuf_AddDesc_delay_2eproto() GOOGLE_ATTRIBUTE_COLD;
void protobuf_AddDesc_delay_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\013delay.proto\022\014delayMessage\"\362\002\n\010DelayMsg"
    "\022\013\n\003cmd\030d \001(\t\022\013\n\003str\030e \001(\t\022\016\n\006msg_id\030\001 \001"
    "(\r\022\021\n\tsend_time\030\002 \001(\001\022\016\n\006uav_id\030\003 \001(\r\022\013\n"
    "\003lat\030\004 \001(\001\022\013\n\003lon\030\005 \001(\001\022\013\n\003alt\030\006 \001(\001\022\n\n\002"
    "vx\030\007 \001(\001\022\n\n\002vy\030\010 \001(\001\022\n\n\002vz\030\t \001(\001\022\t\n\001x\030\n "
    "\001(\001\022\t\n\001y\030\013 \001(\001\022\t\n\001z\030\014 \001(\001\022\t\n\001w\030\r \001(\001\022\013\n\003"
    "gps\030\016 \001(\r\022\025\n\rflight_status\030\017 \001(\r\022\030\n\020is_f"
    "rom_keyboard\030\020 \001(\010\022\022\n\ntarget_lat\030\021 \001(\001\022\022"
    "\n\ntarget_lon\030\022 \001(\001\022\022\n\ntarget_alt\030\023 \001(\001\022\014"
    "\n\004vl_x\030\025 \003(\001\022\014\n\004vl_y\030\026 \003(\001\022\014\n\004vl_z\030\027 \003(\001"
    "b\006proto3", 408);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "delay.proto", &protobuf_RegisterTypes);
  DelayMsg::default_instance_ = new DelayMsg();
  DelayMsg::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_delay_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_delay_2eproto {
  StaticDescriptorInitializer_delay_2eproto() {
    protobuf_AddDesc_delay_2eproto();
  }
} static_descriptor_initializer_delay_2eproto_;

// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int DelayMsg::kCmdFieldNumber;
const int DelayMsg::kStrFieldNumber;
const int DelayMsg::kMsgIdFieldNumber;
const int DelayMsg::kSendTimeFieldNumber;
const int DelayMsg::kUavIdFieldNumber;
const int DelayMsg::kLatFieldNumber;
const int DelayMsg::kLonFieldNumber;
const int DelayMsg::kAltFieldNumber;
const int DelayMsg::kVxFieldNumber;
const int DelayMsg::kVyFieldNumber;
const int DelayMsg::kVzFieldNumber;
const int DelayMsg::kXFieldNumber;
const int DelayMsg::kYFieldNumber;
const int DelayMsg::kZFieldNumber;
const int DelayMsg::kWFieldNumber;
const int DelayMsg::kGpsFieldNumber;
const int DelayMsg::kFlightStatusFieldNumber;
const int DelayMsg::kIsFromKeyboardFieldNumber;
const int DelayMsg::kTargetLatFieldNumber;
const int DelayMsg::kTargetLonFieldNumber;
const int DelayMsg::kTargetAltFieldNumber;
const int DelayMsg::kVlXFieldNumber;
const int DelayMsg::kVlYFieldNumber;
const int DelayMsg::kVlZFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

DelayMsg::DelayMsg()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:delayMessage.DelayMsg)
}

void DelayMsg::InitAsDefaultInstance() {
  _is_default_instance_ = true;
}

DelayMsg::DelayMsg(const DelayMsg& from)
  : ::google::protobuf::Message(),
    _internal_metadata_(NULL) {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:delayMessage.DelayMsg)
}

void DelayMsg::SharedCtor() {
    _is_default_instance_ = false;
  ::google::protobuf::internal::GetEmptyString();
  _cached_size_ = 0;
  cmd_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  str_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  msg_id_ = 0u;
  send_time_ = 0;
  uav_id_ = 0u;
  lat_ = 0;
  lon_ = 0;
  alt_ = 0;
  vx_ = 0;
  vy_ = 0;
  vz_ = 0;
  x_ = 0;
  y_ = 0;
  z_ = 0;
  w_ = 0;
  gps_ = 0u;
  flight_status_ = 0u;
  is_from_keyboard_ = false;
  target_lat_ = 0;
  target_lon_ = 0;
  target_alt_ = 0;
}

DelayMsg::~DelayMsg() {
  // @@protoc_insertion_point(destructor:delayMessage.DelayMsg)
  SharedDtor();
}

void DelayMsg::SharedDtor() {
  cmd_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  str_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (this != default_instance_) {
  }
}

void DelayMsg::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* DelayMsg::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return DelayMsg_descriptor_;
}

const DelayMsg& DelayMsg::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_delay_2eproto();
  return *default_instance_;
}

DelayMsg* DelayMsg::default_instance_ = NULL;

DelayMsg* DelayMsg::New(::google::protobuf::Arena* arena) const {
  DelayMsg* n = new DelayMsg;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void DelayMsg::Clear() {
// @@protoc_insertion_point(message_clear_start:delayMessage.DelayMsg)
#if defined(__clang__)
#define ZR_HELPER_(f) \
  _Pragma("clang diagnostic push") \
  _Pragma("clang diagnostic ignored \"-Winvalid-offsetof\"") \
  __builtin_offsetof(DelayMsg, f) \
  _Pragma("clang diagnostic pop")
#else
#define ZR_HELPER_(f) reinterpret_cast<char*>(\
  &reinterpret_cast<DelayMsg*>(16)->f)
#endif

#define ZR_(first, last) do {\
  ::memset(&first, 0,\
           ZR_HELPER_(last) - ZR_HELPER_(first) + sizeof(last));\
} while (0)

  ZR_(send_time_, alt_);
  cmd_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  str_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  ZR_(vx_, gps_);
  ZR_(flight_status_, target_alt_);
  is_from_keyboard_ = false;

#undef ZR_HELPER_
#undef ZR_

  vl_x_.Clear();
  vl_y_.Clear();
  vl_z_.Clear();
}

bool DelayMsg::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:delayMessage.DelayMsg)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(16383);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional uint32 msg_id = 1;
      case 1: {
        if (tag == 8) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &msg_id_)));

        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(17)) goto parse_send_time;
        break;
      }

      // optional double send_time = 2;
      case 2: {
        if (tag == 17) {
         parse_send_time:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 input, &send_time_)));

        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(24)) goto parse_uav_id;
        break;
      }

      // optional uint32 uav_id = 3;
      case 3: {
        if (tag == 24) {
         parse_uav_id:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &uav_id_)));

        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(33)) goto parse_lat;
        break;
      }

      // optional double lat = 4;
      case 4: {
        if (tag == 33) {
         parse_lat:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 input, &lat_)));

        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(41)) goto parse_lon;
        break;
      }

      // optional double lon = 5;
      case 5: {
        if (tag == 41) {
         parse_lon:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 input, &lon_)));

        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(49)) goto parse_alt;
        break;
      }

      // optional double alt = 6;
      case 6: {
        if (tag == 49) {
         parse_alt:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 input, &alt_)));

        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(57)) goto parse_vx;
        break;
      }

      // optional double vx = 7;
      case 7: {
        if (tag == 57) {
         parse_vx:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 input, &vx_)));

        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(65)) goto parse_vy;
        break;
      }

      // optional double vy = 8;
      case 8: {
        if (tag == 65) {
         parse_vy:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 input, &vy_)));

        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(73)) goto parse_vz;
        break;
      }

      // optional double vz = 9;
      case 9: {
        if (tag == 73) {
         parse_vz:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 input, &vz_)));

        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(81)) goto parse_x;
        break;
      }

      // optional double x = 10;
      case 10: {
        if (tag == 81) {
         parse_x:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 input, &x_)));

        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(89)) goto parse_y;
        break;
      }

      // optional double y = 11;
      case 11: {
        if (tag == 89) {
         parse_y:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 input, &y_)));

        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(97)) goto parse_z;
        break;
      }

      // optional double z = 12;
      case 12: {
        if (tag == 97) {
         parse_z:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 input, &z_)));

        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(105)) goto parse_w;
        break;
      }

      // optional double w = 13;
      case 13: {
        if (tag == 105) {
         parse_w:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 input, &w_)));

        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(112)) goto parse_gps;
        break;
      }

      // optional uint32 gps = 14;
      case 14: {
        if (tag == 112) {
         parse_gps:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &gps_)));

        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(120)) goto parse_flight_status;
        break;
      }

      // optional uint32 flight_status = 15;
      case 15: {
        if (tag == 120) {
         parse_flight_status:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &flight_status_)));

        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(128)) goto parse_is_from_keyboard;
        break;
      }

      // optional bool is_from_keyboard = 16;
      case 16: {
        if (tag == 128) {
         parse_is_from_keyboard:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   bool, ::google::protobuf::internal::WireFormatLite::TYPE_BOOL>(
                 input, &is_from_keyboard_)));

        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(137)) goto parse_target_lat;
        break;
      }

      // optional double target_lat = 17;
      case 17: {
        if (tag == 137) {
         parse_target_lat:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 input, &target_lat_)));

        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(145)) goto parse_target_lon;
        break;
      }

      // optional double target_lon = 18;
      case 18: {
        if (tag == 145) {
         parse_target_lon:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 input, &target_lon_)));

        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(153)) goto parse_target_alt;
        break;
      }

      // optional double target_alt = 19;
      case 19: {
        if (tag == 153) {
         parse_target_alt:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 input, &target_alt_)));

        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(170)) goto parse_vl_x;
        break;
      }

      // repeated double vl_x = 21;
      case 21: {
        if (tag == 170) {
         parse_vl_x:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPackedPrimitive<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 input, this->mutable_vl_x())));
        } else if (tag == 169) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadRepeatedPrimitiveNoInline<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 2, 170, input, this->mutable_vl_x())));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(178)) goto parse_vl_y;
        break;
      }

      // repeated double vl_y = 22;
      case 22: {
        if (tag == 178) {
         parse_vl_y:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPackedPrimitive<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 input, this->mutable_vl_y())));
        } else if (tag == 177) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadRepeatedPrimitiveNoInline<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 2, 178, input, this->mutable_vl_y())));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(186)) goto parse_vl_z;
        break;
      }

      // repeated double vl_z = 23;
      case 23: {
        if (tag == 186) {
         parse_vl_z:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPackedPrimitive<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 input, this->mutable_vl_z())));
        } else if (tag == 185) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadRepeatedPrimitiveNoInline<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 2, 186, input, this->mutable_vl_z())));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(802)) goto parse_cmd;
        break;
      }

      // optional string cmd = 100;
      case 100: {
        if (tag == 802) {
         parse_cmd:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_cmd()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->cmd().data(), this->cmd().length(),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "delayMessage.DelayMsg.cmd"));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(810)) goto parse_str;
        break;
      }

      // optional string str = 101;
      case 101: {
        if (tag == 810) {
         parse_str:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_str()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->str().data(), this->str().length(),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "delayMessage.DelayMsg.str"));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(input, tag));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:delayMessage.DelayMsg)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:delayMessage.DelayMsg)
  return false;
#undef DO_
}

void DelayMsg::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:delayMessage.DelayMsg)
  // optional uint32 msg_id = 1;
  if (this->msg_id() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(1, this->msg_id(), output);
  }

  // optional double send_time = 2;
  if (this->send_time() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteDouble(2, this->send_time(), output);
  }

  // optional uint32 uav_id = 3;
  if (this->uav_id() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(3, this->uav_id(), output);
  }

  // optional double lat = 4;
  if (this->lat() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteDouble(4, this->lat(), output);
  }

  // optional double lon = 5;
  if (this->lon() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteDouble(5, this->lon(), output);
  }

  // optional double alt = 6;
  if (this->alt() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteDouble(6, this->alt(), output);
  }

  // optional double vx = 7;
  if (this->vx() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteDouble(7, this->vx(), output);
  }

  // optional double vy = 8;
  if (this->vy() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteDouble(8, this->vy(), output);
  }

  // optional double vz = 9;
  if (this->vz() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteDouble(9, this->vz(), output);
  }

  // optional double x = 10;
  if (this->x() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteDouble(10, this->x(), output);
  }

  // optional double y = 11;
  if (this->y() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteDouble(11, this->y(), output);
  }

  // optional double z = 12;
  if (this->z() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteDouble(12, this->z(), output);
  }

  // optional double w = 13;
  if (this->w() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteDouble(13, this->w(), output);
  }

  // optional uint32 gps = 14;
  if (this->gps() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(14, this->gps(), output);
  }

  // optional uint32 flight_status = 15;
  if (this->flight_status() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(15, this->flight_status(), output);
  }

  // optional bool is_from_keyboard = 16;
  if (this->is_from_keyboard() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteBool(16, this->is_from_keyboard(), output);
  }

  // optional double target_lat = 17;
  if (this->target_lat() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteDouble(17, this->target_lat(), output);
  }

  // optional double target_lon = 18;
  if (this->target_lon() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteDouble(18, this->target_lon(), output);
  }

  // optional double target_alt = 19;
  if (this->target_alt() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteDouble(19, this->target_alt(), output);
  }

  // repeated double vl_x = 21;
  if (this->vl_x_size() > 0) {
    ::google::protobuf::internal::WireFormatLite::WriteTag(21, ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED, output);
    output->WriteVarint32(_vl_x_cached_byte_size_);
  }
  for (int i = 0; i < this->vl_x_size(); i++) {
    ::google::protobuf::internal::WireFormatLite::WriteDoubleNoTag(
      this->vl_x(i), output);
  }

  // repeated double vl_y = 22;
  if (this->vl_y_size() > 0) {
    ::google::protobuf::internal::WireFormatLite::WriteTag(22, ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED, output);
    output->WriteVarint32(_vl_y_cached_byte_size_);
  }
  for (int i = 0; i < this->vl_y_size(); i++) {
    ::google::protobuf::internal::WireFormatLite::WriteDoubleNoTag(
      this->vl_y(i), output);
  }

  // repeated double vl_z = 23;
  if (this->vl_z_size() > 0) {
    ::google::protobuf::internal::WireFormatLite::WriteTag(23, ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED, output);
    output->WriteVarint32(_vl_z_cached_byte_size_);
  }
  for (int i = 0; i < this->vl_z_size(); i++) {
    ::google::protobuf::internal::WireFormatLite::WriteDoubleNoTag(
      this->vl_z(i), output);
  }

  // optional string cmd = 100;
  if (this->cmd().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->cmd().data(), this->cmd().length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "delayMessage.DelayMsg.cmd");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      100, this->cmd(), output);
  }

  // optional string str = 101;
  if (this->str().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->str().data(), this->str().length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "delayMessage.DelayMsg.str");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      101, this->str(), output);
  }

  // @@protoc_insertion_point(serialize_end:delayMessage.DelayMsg)
}

::google::protobuf::uint8* DelayMsg::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:delayMessage.DelayMsg)
  // optional uint32 msg_id = 1;
  if (this->msg_id() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(1, this->msg_id(), target);
  }

  // optional double send_time = 2;
  if (this->send_time() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteDoubleToArray(2, this->send_time(), target);
  }

  // optional uint32 uav_id = 3;
  if (this->uav_id() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(3, this->uav_id(), target);
  }

  // optional double lat = 4;
  if (this->lat() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteDoubleToArray(4, this->lat(), target);
  }

  // optional double lon = 5;
  if (this->lon() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteDoubleToArray(5, this->lon(), target);
  }

  // optional double alt = 6;
  if (this->alt() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteDoubleToArray(6, this->alt(), target);
  }

  // optional double vx = 7;
  if (this->vx() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteDoubleToArray(7, this->vx(), target);
  }

  // optional double vy = 8;
  if (this->vy() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteDoubleToArray(8, this->vy(), target);
  }

  // optional double vz = 9;
  if (this->vz() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteDoubleToArray(9, this->vz(), target);
  }

  // optional double x = 10;
  if (this->x() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteDoubleToArray(10, this->x(), target);
  }

  // optional double y = 11;
  if (this->y() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteDoubleToArray(11, this->y(), target);
  }

  // optional double z = 12;
  if (this->z() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteDoubleToArray(12, this->z(), target);
  }

  // optional double w = 13;
  if (this->w() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteDoubleToArray(13, this->w(), target);
  }

  // optional uint32 gps = 14;
  if (this->gps() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(14, this->gps(), target);
  }

  // optional uint32 flight_status = 15;
  if (this->flight_status() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(15, this->flight_status(), target);
  }

  // optional bool is_from_keyboard = 16;
  if (this->is_from_keyboard() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteBoolToArray(16, this->is_from_keyboard(), target);
  }

  // optional double target_lat = 17;
  if (this->target_lat() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteDoubleToArray(17, this->target_lat(), target);
  }

  // optional double target_lon = 18;
  if (this->target_lon() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteDoubleToArray(18, this->target_lon(), target);
  }

  // optional double target_alt = 19;
  if (this->target_alt() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteDoubleToArray(19, this->target_alt(), target);
  }

  // repeated double vl_x = 21;
  if (this->vl_x_size() > 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteTagToArray(
      21,
      ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED,
      target);
    target = ::google::protobuf::io::CodedOutputStream::WriteVarint32ToArray(
      _vl_x_cached_byte_size_, target);
  }
  for (int i = 0; i < this->vl_x_size(); i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteDoubleNoTagToArray(this->vl_x(i), target);
  }

  // repeated double vl_y = 22;
  if (this->vl_y_size() > 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteTagToArray(
      22,
      ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED,
      target);
    target = ::google::protobuf::io::CodedOutputStream::WriteVarint32ToArray(
      _vl_y_cached_byte_size_, target);
  }
  for (int i = 0; i < this->vl_y_size(); i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteDoubleNoTagToArray(this->vl_y(i), target);
  }

  // repeated double vl_z = 23;
  if (this->vl_z_size() > 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteTagToArray(
      23,
      ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED,
      target);
    target = ::google::protobuf::io::CodedOutputStream::WriteVarint32ToArray(
      _vl_z_cached_byte_size_, target);
  }
  for (int i = 0; i < this->vl_z_size(); i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteDoubleNoTagToArray(this->vl_z(i), target);
  }

  // optional string cmd = 100;
  if (this->cmd().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->cmd().data(), this->cmd().length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "delayMessage.DelayMsg.cmd");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        100, this->cmd(), target);
  }

  // optional string str = 101;
  if (this->str().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->str().data(), this->str().length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "delayMessage.DelayMsg.str");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        101, this->str(), target);
  }

  // @@protoc_insertion_point(serialize_to_array_end:delayMessage.DelayMsg)
  return target;
}

int DelayMsg::ByteSize() const {
// @@protoc_insertion_point(message_byte_size_start:delayMessage.DelayMsg)
  int total_size = 0;

  // optional string cmd = 100;
  if (this->cmd().size() > 0) {
    total_size += 2 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->cmd());
  }

  // optional string str = 101;
  if (this->str().size() > 0) {
    total_size += 2 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->str());
  }

  // optional uint32 msg_id = 1;
  if (this->msg_id() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt32Size(
        this->msg_id());
  }

  // optional double send_time = 2;
  if (this->send_time() != 0) {
    total_size += 1 + 8;
  }

  // optional uint32 uav_id = 3;
  if (this->uav_id() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt32Size(
        this->uav_id());
  }

  // optional double lat = 4;
  if (this->lat() != 0) {
    total_size += 1 + 8;
  }

  // optional double lon = 5;
  if (this->lon() != 0) {
    total_size += 1 + 8;
  }

  // optional double alt = 6;
  if (this->alt() != 0) {
    total_size += 1 + 8;
  }

  // optional double vx = 7;
  if (this->vx() != 0) {
    total_size += 1 + 8;
  }

  // optional double vy = 8;
  if (this->vy() != 0) {
    total_size += 1 + 8;
  }

  // optional double vz = 9;
  if (this->vz() != 0) {
    total_size += 1 + 8;
  }

  // optional double x = 10;
  if (this->x() != 0) {
    total_size += 1 + 8;
  }

  // optional double y = 11;
  if (this->y() != 0) {
    total_size += 1 + 8;
  }

  // optional double z = 12;
  if (this->z() != 0) {
    total_size += 1 + 8;
  }

  // optional double w = 13;
  if (this->w() != 0) {
    total_size += 1 + 8;
  }

  // optional uint32 gps = 14;
  if (this->gps() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt32Size(
        this->gps());
  }

  // optional uint32 flight_status = 15;
  if (this->flight_status() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt32Size(
        this->flight_status());
  }

  // optional bool is_from_keyboard = 16;
  if (this->is_from_keyboard() != 0) {
    total_size += 2 + 1;
  }

  // optional double target_lat = 17;
  if (this->target_lat() != 0) {
    total_size += 2 + 8;
  }

  // optional double target_lon = 18;
  if (this->target_lon() != 0) {
    total_size += 2 + 8;
  }

  // optional double target_alt = 19;
  if (this->target_alt() != 0) {
    total_size += 2 + 8;
  }

  // repeated double vl_x = 21;
  {
    int data_size = 0;
    data_size = 8 * this->vl_x_size();
    if (data_size > 0) {
      total_size += 2 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(data_size);
    }
    GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
    _vl_x_cached_byte_size_ = data_size;
    GOOGLE_SAFE_CONCURRENT_WRITES_END();
    total_size += data_size;
  }

  // repeated double vl_y = 22;
  {
    int data_size = 0;
    data_size = 8 * this->vl_y_size();
    if (data_size > 0) {
      total_size += 2 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(data_size);
    }
    GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
    _vl_y_cached_byte_size_ = data_size;
    GOOGLE_SAFE_CONCURRENT_WRITES_END();
    total_size += data_size;
  }

  // repeated double vl_z = 23;
  {
    int data_size = 0;
    data_size = 8 * this->vl_z_size();
    if (data_size > 0) {
      total_size += 2 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(data_size);
    }
    GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
    _vl_z_cached_byte_size_ = data_size;
    GOOGLE_SAFE_CONCURRENT_WRITES_END();
    total_size += data_size;
  }

  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void DelayMsg::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:delayMessage.DelayMsg)
  if (GOOGLE_PREDICT_FALSE(&from == this)) {
    ::google::protobuf::internal::MergeFromFail(__FILE__, __LINE__);
  }
  const DelayMsg* source = 
      ::google::protobuf::internal::DynamicCastToGenerated<const DelayMsg>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:delayMessage.DelayMsg)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:delayMessage.DelayMsg)
    MergeFrom(*source);
  }
}

void DelayMsg::MergeFrom(const DelayMsg& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:delayMessage.DelayMsg)
  if (GOOGLE_PREDICT_FALSE(&from == this)) {
    ::google::protobuf::internal::MergeFromFail(__FILE__, __LINE__);
  }
  vl_x_.MergeFrom(from.vl_x_);
  vl_y_.MergeFrom(from.vl_y_);
  vl_z_.MergeFrom(from.vl_z_);
  if (from.cmd().size() > 0) {

    cmd_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.cmd_);
  }
  if (from.str().size() > 0) {

    str_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.str_);
  }
  if (from.msg_id() != 0) {
    set_msg_id(from.msg_id());
  }
  if (from.send_time() != 0) {
    set_send_time(from.send_time());
  }
  if (from.uav_id() != 0) {
    set_uav_id(from.uav_id());
  }
  if (from.lat() != 0) {
    set_lat(from.lat());
  }
  if (from.lon() != 0) {
    set_lon(from.lon());
  }
  if (from.alt() != 0) {
    set_alt(from.alt());
  }
  if (from.vx() != 0) {
    set_vx(from.vx());
  }
  if (from.vy() != 0) {
    set_vy(from.vy());
  }
  if (from.vz() != 0) {
    set_vz(from.vz());
  }
  if (from.x() != 0) {
    set_x(from.x());
  }
  if (from.y() != 0) {
    set_y(from.y());
  }
  if (from.z() != 0) {
    set_z(from.z());
  }
  if (from.w() != 0) {
    set_w(from.w());
  }
  if (from.gps() != 0) {
    set_gps(from.gps());
  }
  if (from.flight_status() != 0) {
    set_flight_status(from.flight_status());
  }
  if (from.is_from_keyboard() != 0) {
    set_is_from_keyboard(from.is_from_keyboard());
  }
  if (from.target_lat() != 0) {
    set_target_lat(from.target_lat());
  }
  if (from.target_lon() != 0) {
    set_target_lon(from.target_lon());
  }
  if (from.target_alt() != 0) {
    set_target_alt(from.target_alt());
  }
}

void DelayMsg::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:delayMessage.DelayMsg)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void DelayMsg::CopyFrom(const DelayMsg& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:delayMessage.DelayMsg)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool DelayMsg::IsInitialized() const {

  return true;
}

void DelayMsg::Swap(DelayMsg* other) {
  if (other == this) return;
  InternalSwap(other);
}
void DelayMsg::InternalSwap(DelayMsg* other) {
  cmd_.Swap(&other->cmd_);
  str_.Swap(&other->str_);
  std::swap(msg_id_, other->msg_id_);
  std::swap(send_time_, other->send_time_);
  std::swap(uav_id_, other->uav_id_);
  std::swap(lat_, other->lat_);
  std::swap(lon_, other->lon_);
  std::swap(alt_, other->alt_);
  std::swap(vx_, other->vx_);
  std::swap(vy_, other->vy_);
  std::swap(vz_, other->vz_);
  std::swap(x_, other->x_);
  std::swap(y_, other->y_);
  std::swap(z_, other->z_);
  std::swap(w_, other->w_);
  std::swap(gps_, other->gps_);
  std::swap(flight_status_, other->flight_status_);
  std::swap(is_from_keyboard_, other->is_from_keyboard_);
  std::swap(target_lat_, other->target_lat_);
  std::swap(target_lon_, other->target_lon_);
  std::swap(target_alt_, other->target_alt_);
  vl_x_.UnsafeArenaSwap(&other->vl_x_);
  vl_y_.UnsafeArenaSwap(&other->vl_y_);
  vl_z_.UnsafeArenaSwap(&other->vl_z_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata DelayMsg::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = DelayMsg_descriptor_;
  metadata.reflection = DelayMsg_reflection_;
  return metadata;
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// DelayMsg

// optional string cmd = 100;
void DelayMsg::clear_cmd() {
  cmd_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 const ::std::string& DelayMsg::cmd() const {
  // @@protoc_insertion_point(field_get:delayMessage.DelayMsg.cmd)
  return cmd_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void DelayMsg::set_cmd(const ::std::string& value) {
  
  cmd_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:delayMessage.DelayMsg.cmd)
}
 void DelayMsg::set_cmd(const char* value) {
  
  cmd_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:delayMessage.DelayMsg.cmd)
}
 void DelayMsg::set_cmd(const char* value, size_t size) {
  
  cmd_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:delayMessage.DelayMsg.cmd)
}
 ::std::string* DelayMsg::mutable_cmd() {
  
  // @@protoc_insertion_point(field_mutable:delayMessage.DelayMsg.cmd)
  return cmd_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 ::std::string* DelayMsg::release_cmd() {
  // @@protoc_insertion_point(field_release:delayMessage.DelayMsg.cmd)
  
  return cmd_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void DelayMsg::set_allocated_cmd(::std::string* cmd) {
  if (cmd != NULL) {
    
  } else {
    
  }
  cmd_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), cmd);
  // @@protoc_insertion_point(field_set_allocated:delayMessage.DelayMsg.cmd)
}

// optional string str = 101;
void DelayMsg::clear_str() {
  str_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 const ::std::string& DelayMsg::str() const {
  // @@protoc_insertion_point(field_get:delayMessage.DelayMsg.str)
  return str_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void DelayMsg::set_str(const ::std::string& value) {
  
  str_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:delayMessage.DelayMsg.str)
}
 void DelayMsg::set_str(const char* value) {
  
  str_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:delayMessage.DelayMsg.str)
}
 void DelayMsg::set_str(const char* value, size_t size) {
  
  str_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:delayMessage.DelayMsg.str)
}
 ::std::string* DelayMsg::mutable_str() {
  
  // @@protoc_insertion_point(field_mutable:delayMessage.DelayMsg.str)
  return str_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 ::std::string* DelayMsg::release_str() {
  // @@protoc_insertion_point(field_release:delayMessage.DelayMsg.str)
  
  return str_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void DelayMsg::set_allocated_str(::std::string* str) {
  if (str != NULL) {
    
  } else {
    
  }
  str_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), str);
  // @@protoc_insertion_point(field_set_allocated:delayMessage.DelayMsg.str)
}

// optional uint32 msg_id = 1;
void DelayMsg::clear_msg_id() {
  msg_id_ = 0u;
}
 ::google::protobuf::uint32 DelayMsg::msg_id() const {
  // @@protoc_insertion_point(field_get:delayMessage.DelayMsg.msg_id)
  return msg_id_;
}
 void DelayMsg::set_msg_id(::google::protobuf::uint32 value) {
  
  msg_id_ = value;
  // @@protoc_insertion_point(field_set:delayMessage.DelayMsg.msg_id)
}

// optional double send_time = 2;
void DelayMsg::clear_send_time() {
  send_time_ = 0;
}
 double DelayMsg::send_time() const {
  // @@protoc_insertion_point(field_get:delayMessage.DelayMsg.send_time)
  return send_time_;
}
 void DelayMsg::set_send_time(double value) {
  
  send_time_ = value;
  // @@protoc_insertion_point(field_set:delayMessage.DelayMsg.send_time)
}

// optional uint32 uav_id = 3;
void DelayMsg::clear_uav_id() {
  uav_id_ = 0u;
}
 ::google::protobuf::uint32 DelayMsg::uav_id() const {
  // @@protoc_insertion_point(field_get:delayMessage.DelayMsg.uav_id)
  return uav_id_;
}
 void DelayMsg::set_uav_id(::google::protobuf::uint32 value) {
  
  uav_id_ = value;
  // @@protoc_insertion_point(field_set:delayMessage.DelayMsg.uav_id)
}

// optional double lat = 4;
void DelayMsg::clear_lat() {
  lat_ = 0;
}
 double DelayMsg::lat() const {
  // @@protoc_insertion_point(field_get:delayMessage.DelayMsg.lat)
  return lat_;
}
 void DelayMsg::set_lat(double value) {
  
  lat_ = value;
  // @@protoc_insertion_point(field_set:delayMessage.DelayMsg.lat)
}

// optional double lon = 5;
void DelayMsg::clear_lon() {
  lon_ = 0;
}
 double DelayMsg::lon() const {
  // @@protoc_insertion_point(field_get:delayMessage.DelayMsg.lon)
  return lon_;
}
 void DelayMsg::set_lon(double value) {
  
  lon_ = value;
  // @@protoc_insertion_point(field_set:delayMessage.DelayMsg.lon)
}

// optional double alt = 6;
void DelayMsg::clear_alt() {
  alt_ = 0;
}
 double DelayMsg::alt() const {
  // @@protoc_insertion_point(field_get:delayMessage.DelayMsg.alt)
  return alt_;
}
 void DelayMsg::set_alt(double value) {
  
  alt_ = value;
  // @@protoc_insertion_point(field_set:delayMessage.DelayMsg.alt)
}

// optional double vx = 7;
void DelayMsg::clear_vx() {
  vx_ = 0;
}
 double DelayMsg::vx() const {
  // @@protoc_insertion_point(field_get:delayMessage.DelayMsg.vx)
  return vx_;
}
 void DelayMsg::set_vx(double value) {
  
  vx_ = value;
  // @@protoc_insertion_point(field_set:delayMessage.DelayMsg.vx)
}

// optional double vy = 8;
void DelayMsg::clear_vy() {
  vy_ = 0;
}
 double DelayMsg::vy() const {
  // @@protoc_insertion_point(field_get:delayMessage.DelayMsg.vy)
  return vy_;
}
 void DelayMsg::set_vy(double value) {
  
  vy_ = value;
  // @@protoc_insertion_point(field_set:delayMessage.DelayMsg.vy)
}

// optional double vz = 9;
void DelayMsg::clear_vz() {
  vz_ = 0;
}
 double DelayMsg::vz() const {
  // @@protoc_insertion_point(field_get:delayMessage.DelayMsg.vz)
  return vz_;
}
 void DelayMsg::set_vz(double value) {
  
  vz_ = value;
  // @@protoc_insertion_point(field_set:delayMessage.DelayMsg.vz)
}

// optional double x = 10;
void DelayMsg::clear_x() {
  x_ = 0;
}
 double DelayMsg::x() const {
  // @@protoc_insertion_point(field_get:delayMessage.DelayMsg.x)
  return x_;
}
 void DelayMsg::set_x(double value) {
  
  x_ = value;
  // @@protoc_insertion_point(field_set:delayMessage.DelayMsg.x)
}

// optional double y = 11;
void DelayMsg::clear_y() {
  y_ = 0;
}
 double DelayMsg::y() const {
  // @@protoc_insertion_point(field_get:delayMessage.DelayMsg.y)
  return y_;
}
 void DelayMsg::set_y(double value) {
  
  y_ = value;
  // @@protoc_insertion_point(field_set:delayMessage.DelayMsg.y)
}

// optional double z = 12;
void DelayMsg::clear_z() {
  z_ = 0;
}
 double DelayMsg::z() const {
  // @@protoc_insertion_point(field_get:delayMessage.DelayMsg.z)
  return z_;
}
 void DelayMsg::set_z(double value) {
  
  z_ = value;
  // @@protoc_insertion_point(field_set:delayMessage.DelayMsg.z)
}

// optional double w = 13;
void DelayMsg::clear_w() {
  w_ = 0;
}
 double DelayMsg::w() const {
  // @@protoc_insertion_point(field_get:delayMessage.DelayMsg.w)
  return w_;
}
 void DelayMsg::set_w(double value) {
  
  w_ = value;
  // @@protoc_insertion_point(field_set:delayMessage.DelayMsg.w)
}

// optional uint32 gps = 14;
void DelayMsg::clear_gps() {
  gps_ = 0u;
}
 ::google::protobuf::uint32 DelayMsg::gps() const {
  // @@protoc_insertion_point(field_get:delayMessage.DelayMsg.gps)
  return gps_;
}
 void DelayMsg::set_gps(::google::protobuf::uint32 value) {
  
  gps_ = value;
  // @@protoc_insertion_point(field_set:delayMessage.DelayMsg.gps)
}

// optional uint32 flight_status = 15;
void DelayMsg::clear_flight_status() {
  flight_status_ = 0u;
}
 ::google::protobuf::uint32 DelayMsg::flight_status() const {
  // @@protoc_insertion_point(field_get:delayMessage.DelayMsg.flight_status)
  return flight_status_;
}
 void DelayMsg::set_flight_status(::google::protobuf::uint32 value) {
  
  flight_status_ = value;
  // @@protoc_insertion_point(field_set:delayMessage.DelayMsg.flight_status)
}

// optional bool is_from_keyboard = 16;
void DelayMsg::clear_is_from_keyboard() {
  is_from_keyboard_ = false;
}
 bool DelayMsg::is_from_keyboard() const {
  // @@protoc_insertion_point(field_get:delayMessage.DelayMsg.is_from_keyboard)
  return is_from_keyboard_;
}
 void DelayMsg::set_is_from_keyboard(bool value) {
  
  is_from_keyboard_ = value;
  // @@protoc_insertion_point(field_set:delayMessage.DelayMsg.is_from_keyboard)
}

// optional double target_lat = 17;
void DelayMsg::clear_target_lat() {
  target_lat_ = 0;
}
 double DelayMsg::target_lat() const {
  // @@protoc_insertion_point(field_get:delayMessage.DelayMsg.target_lat)
  return target_lat_;
}
 void DelayMsg::set_target_lat(double value) {
  
  target_lat_ = value;
  // @@protoc_insertion_point(field_set:delayMessage.DelayMsg.target_lat)
}

// optional double target_lon = 18;
void DelayMsg::clear_target_lon() {
  target_lon_ = 0;
}
 double DelayMsg::target_lon() const {
  // @@protoc_insertion_point(field_get:delayMessage.DelayMsg.target_lon)
  return target_lon_;
}
 void DelayMsg::set_target_lon(double value) {
  
  target_lon_ = value;
  // @@protoc_insertion_point(field_set:delayMessage.DelayMsg.target_lon)
}

// optional double target_alt = 19;
void DelayMsg::clear_target_alt() {
  target_alt_ = 0;
}
 double DelayMsg::target_alt() const {
  // @@protoc_insertion_point(field_get:delayMessage.DelayMsg.target_alt)
  return target_alt_;
}
 void DelayMsg::set_target_alt(double value) {
  
  target_alt_ = value;
  // @@protoc_insertion_point(field_set:delayMessage.DelayMsg.target_alt)
}

// repeated double vl_x = 21;
int DelayMsg::vl_x_size() const {
  return vl_x_.size();
}
void DelayMsg::clear_vl_x() {
  vl_x_.Clear();
}
 double DelayMsg::vl_x(int index) const {
  // @@protoc_insertion_point(field_get:delayMessage.DelayMsg.vl_x)
  return vl_x_.Get(index);
}
 void DelayMsg::set_vl_x(int index, double value) {
  vl_x_.Set(index, value);
  // @@protoc_insertion_point(field_set:delayMessage.DelayMsg.vl_x)
}
 void DelayMsg::add_vl_x(double value) {
  vl_x_.Add(value);
  // @@protoc_insertion_point(field_add:delayMessage.DelayMsg.vl_x)
}
 const ::google::protobuf::RepeatedField< double >&
DelayMsg::vl_x() const {
  // @@protoc_insertion_point(field_list:delayMessage.DelayMsg.vl_x)
  return vl_x_;
}
 ::google::protobuf::RepeatedField< double >*
DelayMsg::mutable_vl_x() {
  // @@protoc_insertion_point(field_mutable_list:delayMessage.DelayMsg.vl_x)
  return &vl_x_;
}

// repeated double vl_y = 22;
int DelayMsg::vl_y_size() const {
  return vl_y_.size();
}
void DelayMsg::clear_vl_y() {
  vl_y_.Clear();
}
 double DelayMsg::vl_y(int index) const {
  // @@protoc_insertion_point(field_get:delayMessage.DelayMsg.vl_y)
  return vl_y_.Get(index);
}
 void DelayMsg::set_vl_y(int index, double value) {
  vl_y_.Set(index, value);
  // @@protoc_insertion_point(field_set:delayMessage.DelayMsg.vl_y)
}
 void DelayMsg::add_vl_y(double value) {
  vl_y_.Add(value);
  // @@protoc_insertion_point(field_add:delayMessage.DelayMsg.vl_y)
}
 const ::google::protobuf::RepeatedField< double >&
DelayMsg::vl_y() const {
  // @@protoc_insertion_point(field_list:delayMessage.DelayMsg.vl_y)
  return vl_y_;
}
 ::google::protobuf::RepeatedField< double >*
DelayMsg::mutable_vl_y() {
  // @@protoc_insertion_point(field_mutable_list:delayMessage.DelayMsg.vl_y)
  return &vl_y_;
}

// repeated double vl_z = 23;
int DelayMsg::vl_z_size() const {
  return vl_z_.size();
}
void DelayMsg::clear_vl_z() {
  vl_z_.Clear();
}
 double DelayMsg::vl_z(int index) const {
  // @@protoc_insertion_point(field_get:delayMessage.DelayMsg.vl_z)
  return vl_z_.Get(index);
}
 void DelayMsg::set_vl_z(int index, double value) {
  vl_z_.Set(index, value);
  // @@protoc_insertion_point(field_set:delayMessage.DelayMsg.vl_z)
}
 void DelayMsg::add_vl_z(double value) {
  vl_z_.Add(value);
  // @@protoc_insertion_point(field_add:delayMessage.DelayMsg.vl_z)
}
 const ::google::protobuf::RepeatedField< double >&
DelayMsg::vl_z() const {
  // @@protoc_insertion_point(field_list:delayMessage.DelayMsg.vl_z)
  return vl_z_;
}
 ::google::protobuf::RepeatedField< double >*
DelayMsg::mutable_vl_z() {
  // @@protoc_insertion_point(field_mutable_list:delayMessage.DelayMsg.vl_z)
  return &vl_z_;
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)

}  // namespace delayMessage

// @@protoc_insertion_point(global_scope)
